name: "Setup"
description: "Setups Node.js and Yarn to run GitHub Actions' jobs."
runs:
  using: "composite"
  steps:
    - name: "Setup Node.js"
      uses: "actions/setup-node@v3"
      with:
        node-version: "20.x"

    - name: "Install dependencies"
      run: "yarn install --frozen-lockfile"
      shell: "bash"
