name: "Continuous Integrations"

on:
  push:
    branches: ["development", "main"]

jobs:
  lint:
    name: "Run ESLint and Prettier"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Setup Node.js and Yarn"
        uses: "./.github/actions/setup"

      - name: "Execute the lint script"
        run: "yarn run lint"

  bundle:
    name: "Bundle package with Rollup.js"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Setup Node.js and Yarn"
        uses: "./.github/actions/setup"

      - name: "Execute the build script"
        run: "yarn run build"
